### ISSUE TITLE
Dashboards should show donation progress of active projects/redesign sidebar?

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#117]
Ideally it would be shown tiny in the sidebar (maybe similar style to how github issues shows "3/10 complete" for tracking issues) and larger in the project description (with number of days left, similar to project badges on homepage).

**Comment by andylouisqin** [comment]
The progress bars makes sense for the ambassador dashboard, since it lists active projects. Wondering if we also want one each for donor and admin dashboards? 

The admin sidebar only seems to list proposed projects (where progress is always 0%). The donor dashboard intends to have solar log data (which means project is funded and progress is always 100%).

**Comment by noahsark769** [comment]
Nope, the progress care should only go on active projects

**Comment by noahsark769** [comment]
Fue completada en la #161
