### ISSUE TITLE
Repayment and Reinvestment Backend Refactor

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#30]
Each project has an associated IRR (Internal Rate of Return). We need to use that IRR to calculate return on investment. Each month they will get some percentage of money back. Some of that money goes to revolv and the rest goes into a pool that can be reinvested. Suppose they get $100 back. $7 might go to revolv and then the remaining $93 could be reinvested. 

I was thinking there could be a new payment object, revolv_bank, which would keep track of how much re-volv itself has to reinvest. The revolv_bank could then make its own donation towards a project, just like any other payment, allowing money to be reinvested. 

Here's the tricky part: The reinvestment by revolv_bank needs to tie back to the donors some how so they can see how their money propagated through the system. So if Person A donates to project 1 and then revolv_bank donates the ROI on project 1 to project 2, Person A should see some of their impact on project 2. This gets more complicated by the fact that Person B could donate to project 2. If the returns from project 2 are reinvested in project 3, Person A should see impact on projects 1, 2, and 3 and Person B should see impacts on projects 2 and 3.

**Comment by noahsark769** [comment]
Alright guys, this issue is getting an EXTREME MAKEOVER, REVOLV EDITION!!

We're gunna refactor how the payments backend works in order to make it a little more scalable and less complicated. Here's the gist:

The new `Payment` model being merged in in #144 has a `user` field and an `entrant` field. The idea is that the `Payment` model will be used both for ORGANIC DONATIONS, in which the user is the same as the entrant and the `payment_instrument` will be paypal, credit card, stripe if we implement it, check if manually entered, etc.

In the case of a check donation given directly to RE-volv, the user may or may not be the same as the entrant, but the `payment_instrument` will always be `name="check"`.

Each `Payment` will have an associated user and a project, the project that it is a donation towards. It will also have zero or more associated `AdminRepayment` models. When an administrator enters a repayment, one of these models will be created. It will have a value (for bookkeeping purposes) and also an associated `RepaymentWeight`. Each `RepaymentWeight` ties an `AdminRepayment` to a User and has a float representing how much of the repayment should be available to the user, based on how much they initially donated to the project.

A reinvestment, when entered in by an administrator, will act exactly like a regular `Payment` to a project, except that it will have a `payment_instrument` of `name="reinvestment"`. It will look as if the User associated with the reinvestment payment had made the donation organically, except for the type of the payment being `reinvestment`. In this way, when the reinvested money is repayed, the user will continue to receive benefits, down to a specified granularity (like 1 cent, etc). This granularity can be hardcoded.

Also, we'll have a `Reinvestment` object which should simply be a collection of `Payment`s that are reinvestments. This will allow us to undo a reinvestment if the administrator makes a mistake (repayments can be undone similarly just by deleting the `AdministratorRepayment` model.

In general, when the admin clicks the Reinvest button with a specific dollar amount x, we should have an algorithm with efficiently allocates x dollars from ALL unsatisfied `AdminRepayments`. An unsatisfied `AdminRepayment` here is one in which the sum of the weights it has does not equal 1. We should also try to allocate money from weights which are associated with check payments first, so that users can "have" as much money available as possible.

This is a BIG part of the project!
